export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME";
export const DELETE_VIDEOGAME = "DELETE_VIDEOGAME"
export const GET_GENRES = "GET_GENRES"
export const SEARCH = "SEARCH"
export const ORDER_ABC = "ORDER_ABC"
export const FILTER_BY_GENRES = "FILTER_BY_GENRES"
export const FILTER_BY_RATING = "FILTER_BY_RATING"

